var IndexConstants = {
  EVENTS_RECEIVED: "EVENTS_RECEIVED",
  EVENT_SPLITS_RECEIVED: "EVENT_SPLITS_RECEIVED",
  TRANSACTIONS_RECEIVED: "TRANSACTIONS_RECEIVED",
  NEW_EVENT_RECEIVED: "NEW_EVENT_RECEIVED",
  // NEW_SPLITS_RECEIVED: "NEW_SPLITS_RECEIVED",
  NEW_TRANSACTION_RECEIVED: "NEW_TRANSACTION_RECEIVED",
  USER_TRANSACTIONS_RECEIVED: "USER_TRANSACTIONS_RECEIVED",
  USER_SPLITS_RECEIVED: "USER_SPLITS_RECEIVED",
  RESET_USER_INDEX: "RESET_USER_INDEX"
};

module.exports = IndexConstants;
