var IndexConstants = {
  EVENTS_RECEIVED: "EVENTS_RECEIVED",
  EVENT_SPLITS_RECEIVED: "EVENT_SPLITS_RECEIVED",
  TRANSACTIONS_RECEIVED: "TRANSACTIONS_RECEIVED",
  NEW_EVENT_RECEIVED: "NEW_EVENT_RECEIVED",
  // NEW_SPLITS_RECEIVED: "NEW_SPLITS_RECEIVED",
  NEW_TRANSACTION_RECEIVED: "NEW_TRANSACTION_RECEIVED"
};

module.exports = IndexConstants;
